// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSXeD6V3ARMCYMwp8jm_Nmnd5LwafvdPw',
    appId: '1:1050577069246:web:02bdffcbad45ab9d826aef',
    messagingSenderId: '1050577069246',
    projectId: 'workspace-booking-task',
    authDomain: 'workspace-booking-task.firebaseapp.com',
    storageBucket: 'workspace-booking-task.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8ATdMEjEeiu2p1pilrGrgubQZcpNsEPw',
    appId: '1:1050577069246:android:1712d54885bdf9ba826aef',
    messagingSenderId: '1050577069246',
    projectId: 'workspace-booking-task',
    storageBucket: 'workspace-booking-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_G_SZ8X5m7yl5kIhizvea3dltczT4bt0',
    appId: '1:1050577069246:ios:1fac96bdbe40115f826aef',
    messagingSenderId: '1050577069246',
    projectId: 'workspace-booking-task',
    storageBucket: 'workspace-booking-task.appspot.com',
    iosBundleId: 'com.workspace.booking.workspaceBooking',
  );

}